default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key
  - repo: local
    hooks:
      - id: clean
        name: clean
        entry: poe
        args: [ "clean" ]
        language: system
        pass_filenames: false
      - id: format
        name: format
        entry: poe
        args: [ "format" ]
        language: system
        pass_filenames: false
      - id: lint
        name: lint
        entry: poe
        args: [ "lint" ]
        language: system
        pass_filenames: false
      - id: tests
        name: tests
        entry: poe
        args: [ "tests" ]
        language: system
        pass_filenames: false
