default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
      - id: black
        verbose: true
        args: [ --config=pyproject.toml ]
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.1.0
    hooks:
      - id: pycln
        verbose: true
        args: [ --config=pyproject.toml ]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        verbose: true
        args: [ --settings-path pyproject.toml ]
