# Automatically merge Dependabot PRs when version comparison is within range
#
# Requires GitHub secrets
# - GH_TOKEN

name: Dependabot auto merge

on:
  pull_request:
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: checkout-repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run action
        id: run-action
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GH_TOKEN }}
