# Continuous deployment workflow
# - Check status of the CI workflow
# - Create release
# - Deploy package on PYPI
#
# Requires GitHub secrets
# - PYPI_TOKEN

name: CD

on:
  push:
    branches:
      - main

jobs:
  semantic_release:
    name: Create semantic release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry python-semantic-release
          python -m poetry install
      - name: Semantic release
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          semantic-release publish -D commit_author="github-actions <github-actions@github.com>"
  deploy_pypi:
    name: Build and publish package
    needs: [ semantic_release ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Build package
        run: python -m poetry build
      - name: Publish package
        run: |
          python -m poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          python -m poetry publish
