# Continuous deployment workflow
# - Check status of the CI workflow
# - Create release
# - Deploy package on PYPI
#
# Requires GitHub secrets
# - GITHUB_TOKEN
# - PYPI_TOKEN

name: CD

on:
  push:
    branches:
      - main

jobs:
  check_ci:
    name: Check CI status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests jmespath
      - name: Check the last master push CI status
        run: |
          python .github/status.py
  create_release:
    name: Create release
    needs: check_ci
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Python semantic release
        run: |
          pip install python-semantic-release
          git config user.name github-actions
          git config user.email github-actions@github.com
          semantic-release publish
  deploy:
    name: Build and publish package
    needs: [ check_ci, create_release ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Build package
        run: poetry build
      - name: Publish package
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish
