# Continuous deployment workflow
# - Create release
# - Deploy package on GitHub and PYPI
#
# Requires GitHub secrets
# - GH_TOKEN
# - PYPI_TOKEN

name: Deployment

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry python-semantic-release
          python -m poetry install
      - name: Run semantic release
        env:
          github_token: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          semantic-release publish -D commit_author="github-actions <github-actions@github.com>" -v DEBUG
      - name: Build package
        run: python -m poetry build
      - name: Publish package
        run: |
          python -m twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }} --skip-existing
