# Continuous integration workflow
# - Run linters (flake8, mypy, security)
# - Run tests (doctests, unittests)
#
# Requires GitHub secrets
# - CODECOV_TOKEN

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m poetry install
      - name: Run flake8
        run: |
          python -m poetry run pflake8
      - name: Run mypy
        run: |
          python -m poetry run mypy --config-file pyproject.toml
      - name: Run security linters
        run: |
          python -m poetry check
          python -m poetry run pip check
          python -m poetry run safety check --full-report
  tests:
    name: Run tests
    needs: linters
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m poetry install
      - name: Run pytest | xdoctest
        run: |
          python -m poetry run pytest --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.13
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: ${{ matrix.os }}, ${{ matrix.python-version }}
